// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroConDetalle.DAL;

namespace RegistroConDetalle1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200307180114_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("RegistroConDetalle.Entidades.Personas", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimineto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("RegistroConDetalle.Entidades.TelefonosDetalle", b =>
                {
                    b.Property<int>("TelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("TelId");

                    b.HasIndex("PersonasId");

                    b.ToTable("TelefonosDetalle");
                });

            modelBuilder.Entity("RegistroConDetalle.Entidades.TelefonosDetalle", b =>
                {
                    b.HasOne("RegistroConDetalle.Entidades.Personas", null)
                        .WithMany("Telefonos")
                        .HasForeignKey("PersonasId");
                });
#pragma warning restore 612, 618
        }
    }
}
